- name: Playbook
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  vars_files: ./vars.yaml 
  tasks:
    - name: install packages
      package:
        name: "{{packages}}"
        state: present
          
    - name: OhMyZsh
      block:
        - name: Install OhMyZshi
          shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    

    - name: Docker
      block:
        - name: Install Docker 
          package:
            name: "docker"
            state: present

        - name: Docker Start
          service:
            name: docker.service
            state: started
        
        - name: Docker create Docker Group
          group:
            name: docker
            state: present
            gid: 1396

        - name: Get User
          command: whoami
          changed_when: false
          become: false
          register: whoami

        - name: Add User to Docker Group
          user: 
            name: "{{whoami.stdout}}" 
            comment: Admin
            group: docker
      when:
        - ansible_facts['distribution'] == "Archlinux"


